# Generated by Django 3.2.7 on 2021-09-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='SOME STRING', max_length=200, unique=True),
        ),
    ]
