# Generated by Django 3.2.7 on 2021-09-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
