# Generated by Django 3.2.7 on 2021-09-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-Ans_created_on']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-Que_created_on']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='Ans_author',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='body',
            new_name='Ans_body',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='created_on',
            new_name='Ans_created_on',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='Que_author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_on',
            new_name='Que_created_on',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='Que_text',
        ),
    ]
