# Generated by Django 3.2.7 on 2021-09-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20210924_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(choices=[('Python', 'Python'), ('django', 'django'), ('C', 'C'), ('Node.js', 'Node.js'), ('excel', 'excel'), ('pandas', 'pandas'), ('linux', 'linux'), ('data structures', 'data structures'), ('sql', 'sql'), ('other', 'other')], default='other', max_length=100),
        ),
    ]
